### ISSUE TITLE
LIst index out of range

### ISSUE THREAD

**Issue by neopablo2000** [MycroftAI/skill-desktop-launcher#13]
This skill was working ok until yesterday, now its not loading (sorry my english, spanish speaker) with the next error:

`File "/home/pablo/mycroft-core/mycroft/skills/core.py", line 149, in load_skill
    raise e
  File "/home/pablo/mycroft-core/mycroft/skills/core.py", line 145, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/skill-desktop-launcher/__init__.py", line 45, in initialize
    tokenized_name = tokenizer.tokenize(name)[0]
IndexError: list index out of range
`
Ubuntu Mate 18.04
mycroft-core 19.2.14

Any clue? :)

**Comment by forslund** [comment]
I believe @krisgesling fixed this in #14, try updating the skill if it hasn't pulled down the latest automatically. Let us know if it's still an issue.

**Comment by neopablo2000** [comment]
Yes! In fact, he helped me debug this, thank you!!

**Comment by forslund** [comment]
Great to hear. Since it seems resolved I'm closing this issue. Thanks for reporting and helping improving Mycroft!
