### ISSUE TITLE
Unexpected Indent Trying Load Skill

### ISSUE THREAD

**Issue by btotharye** [MycroftAI/skill-desktop-launcher#3]
On a fresh install of mycroft desktop and this skill getting the following:

`2017-06-30 19:37:33,679 - mycroft.skills.core - INFO - ATTEMPTING TO LOAD SKILL: skill-desktop-launcher
2017-06-30 19:37:33,679 - mycroft.skills.core - ERROR - Failed to load skill: skill-desktop-launcher
Traceback (most recent call last):
  File "/home/btotharye/mycroft-core/mycroft/skills/core.py", line 103, in load_skill
    skill_descriptor["name"] + MainModule, *skill_descriptor["info"])
  File "/opt/mycroft/skills/skill-desktop-launcher/__init__.py", line 101
    subprocess.call( [ "killall", "-9", app_name ] )
    ^
IndentationError: unexpected indent`

Code it references:
    def handle_close_desktop_app(self, message):
        app_name = message.data.get('Application')
	subprocess.call( [ "killall", "-9", app_name ] )

Thanks

**Comment by forslund** [comment]
Hmm, I don't get that error but I do think I see the issue. There is a \t among the normal '    ' tabs.

**Comment by forslund** [comment]
@btotharye if you have the time it would be great if you could try out #4.

**Comment by btotharye** [comment]
@forslund just did and it works
